set(_CATKIN_CURRENT_PACKAGE "microstrain_3dm_gx5_45")
set(microstrain_3dm_gx5_45_VERSION "0.0.1")
set(microstrain_3dm_gx5_45_MAINTAINER "Brian Bingham <briansbingham@gmail.com>")
set(microstrain_3dm_gx5_45_PACKAGE_FORMAT "2")
set(microstrain_3dm_gx5_45_BUILD_DEPENDS "roscpp" "cmake_modules" "tf2" "tf2_ros" "std_msgs" "std_srvs" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(microstrain_3dm_gx5_45_BUILD_EXPORT_DEPENDS "roscpp" "cmake_modules" "tf2" "tf2_ros" "std_msgs" "std_srvs" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(microstrain_3dm_gx5_45_BUILDTOOL_DEPENDS "catkin")
set(microstrain_3dm_gx5_45_BUILDTOOL_EXPORT_DEPENDS )
set(microstrain_3dm_gx5_45_EXEC_DEPENDS "roscpp" "cmake_modules" "tf2" "tf2_ros" "std_msgs" "std_srvs" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(microstrain_3dm_gx5_45_RUN_DEPENDS "roscpp" "cmake_modules" "tf2" "tf2_ros" "std_msgs" "std_srvs" "geometry_msgs" "sensor_msgs" "nav_msgs")
set(microstrain_3dm_gx5_45_TEST_DEPENDS )
set(microstrain_3dm_gx5_45_DOC_DEPENDS )
set(microstrain_3dm_gx5_45_URL_WEBSITE "http://wiki.ros.org/microstrain_3dm_gx5_45")
set(microstrain_3dm_gx5_45_URL_BUGTRACKER "")
set(microstrain_3dm_gx5_45_URL_REPOSITORY "")
set(microstrain_3dm_gx5_45_DEPRECATED "")