set(_CATKIN_CURRENT_PACKAGE "hubo_slam")
set(hubo_slam_VERSION "0.0.1")
set(hubo_slam_MAINTAINER "Kent Sommer <kent.sommer13@gmail.com>")
set(hubo_slam_PACKAGE_FORMAT "1")
set(hubo_slam_BUILD_DEPENDS )
set(hubo_slam_BUILD_EXPORT_DEPENDS )
set(hubo_slam_BUILDTOOL_DEPENDS "catkin")
set(hubo_slam_BUILDTOOL_EXPORT_DEPENDS )
set(hubo_slam_EXEC_DEPENDS )
set(hubo_slam_RUN_DEPENDS )
set(hubo_slam_TEST_DEPENDS )
set(hubo_slam_DOC_DEPENDS )
set(hubo_slam_URL_WEBSITE "http://nmail.kaist.ac.kr")
set(hubo_slam_URL_BUGTRACKER "")
set(hubo_slam_URL_REPOSITORY "")
set(hubo_slam_DEPRECATED "")