#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH="/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/microstrain_3dm_gx5_45:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/hubo_slam:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer_rviz:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer_ros:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer_ros_msgs:/home/rainbow/catkin_ws/devel:/opt/ros/kinetic:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/ceres-solver:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/ceres-solver"
export LD_LIBRARY_PATH="/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/microstrain_3dm_gx5_45/lib:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/hubo_slam/lib:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer_rviz/lib:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer_ros/lib:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer_ros_msgs/lib:/home/rainbow/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer/lib:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer/lib/x86_64-linux-gnu:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/ceres-solver/lib:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/ceres-solver/lib/x86_64-linux-gnu:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer/lib:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/ceres-solver/lib:/usr/local/cuda-9.1/lib64/"
export PATH="/opt/ros/kinetic/bin:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer/bin:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/ceres-solver/bin:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer/bin:/usr/local/cuda-9.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
export PKG_CONFIG_PATH="/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/microstrain_3dm_gx5_45/lib/pkgconfig:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/hubo_slam/lib/pkgconfig:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer_rviz/lib/pkgconfig:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer_ros/lib/pkgconfig:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer_ros_msgs/lib/pkgconfig:/home/rainbow/catkin_ws/devel/lib/pkgconfig:/opt/ros/kinetic/lib/pkgconfig:/opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer/lib/pkgconfig:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer/lib/x86_64-linux-gnu/pkgconfig:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/ceres-solver/lib/pkgconfig:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/ceres-solver/lib/x86_64-linux-gnu/pkgconfig"
export PYTHONPATH="/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer_ros_msgs/lib/python2.7/dist-packages:/home/rainbow/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/kinetic/lib/python2.7/dist-packages:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/cartographer/lib/python2.7/dist-packages:/home/rainbow/Desktop/hubo_slam_ws/devel_isolated/ceres-solver/lib/python2.7/dist-packages"